#!/usr/bin/env python
import os
import subprocess
import sys
from pathlib import Path

if len(sys.argv) != 3:
    print("Usage: mkpj project-name private|public|secret")
    exit(1)

_, project_name, publicity = sys.argv


def run(*args):
    return subprocess.run(args, check=True)


project_dir = Path(os.path.expanduser("~")) / "pj" / project_name
os.makedirs(project_dir)
os.chdir(project_dir)
run("ssh", "mygit", "init", project_name, publicity)
run("git", "init")
run("git", "remote", "add", "origin", f"mygit:{project_name}")
print("All done. Have fun.")
